services:
  - type: web
    name: todo-flask
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/test.db
